name: alanfalproject
description: Alanfal E-Commerce Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_auth: ^1.0.3
#  cloud_firestore: ^0.13.4+2
#  provider: ^4.0.4
#  fancy_on_boarding: ^1.5.0
#  shared_preferences: ^0.5.6+3
#  flutter_spinkit: ^4.1.2
#  flutter_blue: ^0.7.1+1
#  uuid: ^2.2.2
#  device_info: ^0.4.0+4
#  flutter_scan_bluetooth: ^1.1.0
#  wifi_info_plugin: ^1.0.6
#  flutter_bluetooth_serial: ^0.2.2
#  app_settings: 3.0.1
#  carousel_pro: ^1.0.0
#  transparent_image: ^1.0.0
#  firebase_database:
#  fluttertoast: ^7.1.5
#  url_launcher: ^5.7.10
#  webview_flutter: ^1.0.7
#  google_fonts: ^1.1.1
  flutter_colorpicker: ^0.3.5
  font_awesome_flutter: ^8.11.0
  page_transition: ^1.1.7+6
  cached_network_image: ^2.5.0
  readmore: ^2.0.0
#  flutter_svg: ^0.20.0-nullsafety.3

  cloud_firestore: ^1.0.4
  provider: ^4.0.4
  fancy_on_boarding: ^1.5.0
  shared_preferences: ^0.5.6+3
  flutter_spinkit: ^4.1.2
  flutter_blue: ^0.7.1+1
  uuid: ^3.0.4
  device_info: ^0.4.0+4
  flutter_scan_bluetooth: ^1.1.0
  wifi_info_plugin: ^1.0.6
  flutter_bluetooth_serial: ^0.2.2
  app_settings: 3.0.1
  carousel_pro: ^1.0.0
  transparent_image: ^1.0.0
  firebase_database:
  fluttertoast: ^7.1.5
  url_launcher: ^6.0.3
  webview_flutter: ^1.0.7
  google_fonts: ^2.0.0
#  firebase_storage: ^7.0.0
  firebase_core: ^1.0.3
#  firebase: ^9.0.1
#  image_picker: ^0.6.7+21
  pin_code_fields: ^7.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  custom_splash: ^0.0.2
dev_dependencies:
  flutter_launcher_icons:  ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/icon.png"
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/car1.png
    - images/car2.png
    - images/car3.png
    - images/cats/rolling_shutter.png
    - images/cats/safety_window.png
    - images/cats/fire_doors.png
    - images/cats/saftey_doors.png
    - images/logo.png
    - images/m2.jpg
    - images/doortest.jpg
    - images/rollingshutter.jpg
    - images/test.gif
    - images/gif/gifshutter.gif
    - images/gif/gifshutter_1.gif
    - images/gif/gifshutter_2.gif
    - images/gif/gifshutter_3.gif
    - images/gif/gifsafewindow.gif
    - images/gif/gifsafewindow_1.gif
    - images/gif/gifsafewindow_2.gif
    - images/gif/gifsafedoor.gif
    - images/gif/gifsafedoor1.gif
    - images/gif/gifsafedoor2.gif
    - images/gif/gifsafedoor3.gif
    - images/gif/gifsafedoor4.gif
    - images/gif/gifsafedoor5.gif
    - images/gif/gifsafedoor6.gif
    - images/gif/gifsafedoor7.gif
    - images/gif/logosplash.gif
    - images/icon/rollingshutterlogo.png
    - images/icon/safetydoorlogo.png
    - images/icon/safetywindowlogo.png
    - images/icon/firedoorlogo.png
    - images/recentworklogo/1.jpg
    - images/recentworklogo/2.jpg
    - images/recentworklogo/3.jpg
    - images/recentworklogo/4.jpg
    - images/recentworklogo/5.jpg
    - images/recentworklogo/6.jpg
    - images/recentworklogo/7.jpg
    - images/recentworklogo/8.jpg
    - images/recentworklogo/9.jpg
    - images/recentworklogo/10.jpg
    - images/recentworklogo/11.jpg
    - images/recentworklogo/12.jpg
    - images/aboutus/aboutusimg1.jpg
    - images/aboutus/aboutusimg2.jpg
    - images/aboutus/aboutusimg3.jpg
    - images/aboutus/aboutusimg4.jpg
    - images/aboutus/aboutusimg5.jpg
    - images/aboutus/aboutusimg6.jpg
    - images/aboutus/aboutusimg7.jpg
    - images/aboutus/aboutusimg8.jpg
    - images/aboutus/aboutusimg9.jpg
    - images/aboutus/aboutusimg10.jpg
    - images/aboutus/aboutusimg11.jpg
    - images/aboutus/aboutusimg12.jpg
    - images/aboutus/aboutusimg13.bmp
    - images/aboutus/aboutusimg14.bmp
    - images/aboutus/aboutusimg15.bmp
    - images/aboutus/aboutusimg16.jpg
    - images/aboutus/aboutusimg17.jpg
    - images/aboutus/aboutusimg18.jpg
    - images/aboutus/aboutusgif1.gif
    - images/firedoor/firedoor-1.png
    - images/firedoor/firedoor-2.png
    - images/firedoor/firedoor-3.png
    - images/firedoor/firedoor-4.png
    - images/curve.jpg








  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
